import { StockAnalysis, MutualFund } from "./types";

// Pre-compiled comprehensive research data for seamless instant explorations of different brackets
// All static financial figures, PE, EPS, dividend yield, and prices are set to "Live data unavailable"
export const PRECOMPILED_STOCKS: Record<string, StockAnalysis> = {
  "TCS": {
    companyName: "Tata Consultancy Services Ltd",
    symbol: "TCS",
    sector: "Information Technology",
    about: "Tata Consultancy Services is an Indian multinational information technology services and consulting company. It operates in 149 locations across 46 countries and is the second-largest Indian company by market capitalization.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: {
      liquidity: [],
      solvency: [],
      efficiency: []
    },
    competitors: [],
    futureGrowth: {
      predictionSummary: "Live growth predictions unavailable. Please search to reconnect.",
      years: []
    },
    investmentResearchSummary: "IT major with strong balance sheet & consistent cash flows; price & volume tracked via live exchange proxy."
  },
  "RELIANCE": {
    companyName: "Reliance Industries Ltd",
    symbol: "RELIANCE",
    sector: "Conglomerate (Oil, Retail, Telecom)",
    about: "Reliance Industries is India's largest private sector conglomerate. It is active in hydrocarbon exploration, petroleum refining, petrochemicals, retail, and telecommunications (Jio).",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: {
      liquidity: [],
      solvency: [],
      efficiency: []
    },
    competitors: [],
    futureGrowth: {
      predictionSummary: "Live growth predictions unavailable. Please search to reconnect.",
      years: []
    },
    investmentResearchSummary: "Diversified energy & retail conglomerate; price & volume tracked via live exchange proxy."
  },
  "YESBANK": {
    companyName: "Yes Bank Ltd",
    symbol: "YESBANK",
    sector: "Banking & Financials (Bottom/Turnaround)",
    about: "Yes Bank is an Indian private sector bank founded in 2004. After facing severe asset-quality issues in 2020, it underwent an RBI-led reconstruction plan with SBI taking major equity.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: {
      liquidity: [],
      solvency: [],
      efficiency: []
    },
    competitors: [],
    futureGrowth: {
      predictionSummary: "Live growth predictions unavailable. Please search to reconnect.",
      years: []
    },
    investmentResearchSummary: "Private sector banking turnaround story; price & volume tracked via live exchange proxy."
  },
  "SUZLON": {
    companyName: "Suzlon Energy Ltd",
    symbol: "SUZLON",
    sector: "Renewable Energy (Lower Bracket/Turnaround)",
    about: "Suzlon is an Indian wind-turbine manufacturing company. It was once India's wind major, went into severe debt/financial restructure, and has successfully staged a clean-debt turnaround with massive government green push.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: {
      liquidity: [],
      solvency: [],
      efficiency: []
    },
    competitors: [],
    futureGrowth: {
      predictionSummary: "Live growth predictions unavailable. Please search to reconnect.",
      years: []
    },
    investmentResearchSummary: "Renewable equipment provider; price & volume tracked via live exchange proxy."
  },
  "INFY": {
    companyName: "Infosys Ltd",
    symbol: "INFY",
    sector: "Information Technology",
    about: "Infosys is a global leader in next-generation digital services and consulting. Operating in over 56 countries, it provides cloud, AI, and enterprise IT transformation.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Tier-1 IT exporter benefiting from AI adoption and enterprise cloud modernization."
  },
  "HDFCBANK": {
    companyName: "HDFC Bank Ltd",
    symbol: "HDFCBANK",
    sector: "Banking & Financial Services",
    about: "HDFC Bank is India's largest private sector bank by assets and market capitalization, offering retail banking, wholesale banking, and credit card services.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Cornerstone financial compounder with strong asset quality and deep retail distribution network."
  },
  "SBIN": {
    companyName: "State Bank of India",
    symbol: "SBIN",
    sector: "Public Sector Banking",
    about: "State Bank of India is a Fortune 500 public sector bank and the largest lender in India with over 22,000 branches and 480 million customers.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "India's banking backbone with expanding net interest margins and record low gross NPAs."
  },
  "ICICIBANK": {
    companyName: "ICICI Bank Ltd",
    symbol: "ICICIBANK",
    sector: "Banking & Financial Services",
    about: "ICICI Bank is a leading private sector bank in India providing a comprehensive suite of banking products and financial services to corporate and retail customers.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Consistently outperforming peers in credit growth, digital banking adoption, and ROA metrics."
  },
  "TATAMOTORS": {
    companyName: "Tata Motors Ltd",
    symbol: "TATAMOTORS",
    sector: "Automotive & Electric Vehicles",
    about: "Tata Motors is a leading global automobile manufacturer producing cars, SUVs, trucks, buses, and commercial vehicles. It dominates the Indian Electric Vehicle (EV) market and owns Jaguar Land Rover (JLR).",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Pioneer in Indian EV transition with strong debt reduction and robust JLR order pipeline."
  },
  "ITC": {
    companyName: "ITC Ltd",
    symbol: "ITC",
    sector: "FMCG & Diversified Conglomerate",
    about: "ITC is an Indian conglomerate with a presence in FMCG (packaged foods, personal care), Cigarettes, Hotels, Paperboards & Specialty Papers, and Agri-Business.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "High dividend yield compounder with rapidly scaling non-cigarette FMCG revenues."
  },
  "BHARTIARTL": {
    companyName: "Bharti Airtel Ltd",
    symbol: "BHARTIARTL",
    sector: "Telecommunications",
    about: "Bharti Airtel is a global communications solutions provider with over 500 million customers across South Asia and 14 African countries.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Telecom duopoly leader benefiting from rising ARPU and nationwide 5G rollouts."
  },
  "LT": {
    companyName: "Larsen & Toubro Ltd",
    symbol: "LT",
    sector: "Construction & Infrastructure",
    about: "Larsen & Toubro is an Indian multinational conglomerate engaged in EPC projects, hi-tech manufacturing, defense, infrastructure, and technology services.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Prime beneficiary of India's capex boom and Middle East infrastructure expansion."
  },
  "SUNPHARMA": {
    companyName: "Sun Pharmaceutical Industries Ltd",
    symbol: "SUNPHARMA",
    sector: "Pharmaceuticals",
    about: "Sun Pharma is India's largest specialty pharmaceutical company, manufacturing and marketing a broad portfolio of generic and branded formulations worldwide.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Global pharma major with market-leading domestic formulations and expanding global specialty portfolio."
  },
  "MARUTI": {
    companyName: "Maruti Suzuki India Ltd",
    symbol: "MARUTI",
    sector: "Automotive (Passenger Vehicles)",
    about: "Maruti Suzuki is India's largest passenger vehicle maker, holding over 40% market share in cars and SUVs with Suzuki Motor Corporation as majority owner.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Domestic auto leader accelerating SUV portfolio expansion and hybrid mobility."
  },
  "ADANIENT": {
    companyName: "Adani Enterprises Ltd",
    symbol: "ADANIENT",
    sector: "Conglomerate & Incubation",
    about: "Adani Enterprises is the flagship incubator company of the Adani Group, focusing on green hydrogen, airports, roads, data centers, and mining.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "High-beta incubation engine driving massive green energy and infrastructure capex."
  },
  "NTPC": {
    companyName: "NTPC Ltd",
    symbol: "NTPC",
    sector: "Power Generation & Utilities",
    about: "NTPC is India's largest power utility corporation, generating over 25% of the nation's electricity with aggressive expansion into solar, wind, and green energy.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Reliable power utility transitioning to 60 GW green power capacity target by 2032."
  },
  "BAJFINANCE": {
    companyName: "Bajaj Finance Ltd",
    symbol: "BAJFINANCE",
    sector: "Non-Banking Financial Company (NBFC)",
    about: "Bajaj Finance is a premier deposit-taking NBFC offering consumer lending, SME loans, commercial lending, wealth management, and payment services across India.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Fintech-driven NBFC leader with industry-leading ROE and customer acquisition momentum."
  },
  "TITAN": {
    companyName: "Titan Company Ltd",
    symbol: "TITAN",
    sector: "Consumer Goods & Lifestyle",
    about: "Titan Company, a joint venture between Tata Group and TIDCO, is India's leading consumer brand in jewelry (Tanishq), watches, and eyewear.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Premium retail powerhouse capturing formalization in Indian jewelry and lifestyle consumption."
  },
  "HAL": {
    companyName: "Hindustan Aeronautics Ltd",
    symbol: "HAL",
    sector: "Defense & Aerospace",
    about: "Hindustan Aeronautics Limited is a premier Indian state-owned aerospace and defense company manufacturing fighter aircraft (Tejas), helicopters, and aero-engines.",
    currentPrice: "Live data unavailable",
    currency: "INR",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Monopolistic defense aerospace giant backed by record multi-decade IAF order book."
  },
  "AAPL": {
    companyName: "Apple Inc",
    symbol: "AAPL",
    sector: "Global Technology & Consumer Hardware",
    about: "Apple designs, manufactures, and markets smartphones (iPhone), personal computers (Mac), tablets (iPad), wearables, and digital services globally.",
    currentPrice: "Live data unavailable",
    currency: "USD",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Global tech benchmark with ecosystem lock-in, expanding services margins, and massive share buybacks."
  },
  "GOOGL": {
    companyName: "Alphabet Inc (Google)",
    symbol: "GOOGL",
    sector: "Global AI & Digital Services",
    about: "Alphabet is a global technology leader operating Google Search, YouTube, Android, Google Cloud, and cutting-edge Gemini AI models.",
    currentPrice: "Live data unavailable",
    currency: "USD",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Search and video ad dominance coupled with hyper-scaling Google Cloud & Gemini AI integration."
  },
  "MSFT": {
    companyName: "Microsoft Corporation",
    symbol: "MSFT",
    sector: "Global Cloud & Enterprise Software",
    about: "Microsoft develops Windows, Office 365, Azure Cloud, AI Copilot solutions, Xbox gaming, and enterprise productivity platforms.",
    currentPrice: "Live data unavailable",
    currency: "USD",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Enterprise cloud and generative AI infrastructure powerhouse driving multi-year SaaS expansion."
  },
  "NVDA": {
    companyName: "NVIDIA Corporation",
    symbol: "NVDA",
    sector: "Global Semiconductors & AI Hardware",
    about: "NVIDIA is the world pioneer in graphics processing units (GPUs) and AI accelerated computing chips powering modern data centers.",
    currentPrice: "Live data unavailable",
    currency: "USD",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Dominant AI compute monopoly providing hardware backbone for global LLMs and data centers."
  },
  "TSLA": {
    companyName: "Tesla Inc",
    symbol: "TSLA",
    sector: "Automotive & Clean Energy",
    about: "Tesla designs, manufactures, and sells electric vehicles, solar energy generation equipment, energy storage systems, and autonomous driving software.",
    currentPrice: "Live data unavailable",
    currency: "USD",
    eps: "Not tracked in free tier",
    peRatio: "Not tracked in free tier",
    pbRatio: "Not tracked in free tier",
    dividendYield: "Not tracked in free tier",
    dividends: [],
    financials: [],
    ratios: { liquidity: [], solvency: [], efficiency: [] },
    competitors: [],
    futureGrowth: { predictionSummary: "Live growth predictions unavailable.", years: [] },
    investmentResearchSummary: "Global EV volume leader expanding into Full Self-Driving (FSD), Megapack storage, and robotics."
  }
};

export const PRECOMPILED_MUTUAL_FUNDS: MutualFund[] = [
  {
    schemeCode: "120828",
    fundName: "Quant Small Cap Fund - Direct Growth",
    category: "Small Cap Equity",
    vintageYears: 11,
    risk: "Very High",
    historicalReturn3Y: 28.5,
    historicalReturn5Y: 24.2,
    currentNav: 315.58,
    expenseRatio: 0.77,
    aum: "₹18,240 Cr",
    reason: "Historically delivers extreme compounding index-beating returns by following high momentum and agile portfolio rotation.",
    similarFunds: ["Nippon India Small Cap Fund", "Tata Small Cap Fund"]
  },
  {
    schemeCode: "122639",
    fundName: "Parag Parikh Flexi Cap Fund - Direct Growth",
    category: "Flexi Cap Equity (Multi Cap)",
    vintageYears: 11,
    risk: "High",
    historicalReturn3Y: 19.8,
    historicalReturn5Y: 18.5,
    currentNav: 92.33,
    expenseRatio: 0.62,
    aum: "₹63,400 Cr",
    reason: "Value-oriented diversified multi-cap holding including global stocks (e.g. Microsoft, Alphabet), offering excellent currency hedging and core compounding.",
    similarFunds: ["HDFC Flexi Cap Fund", "SBI Flexi Cap Fund"]
  },
  {
    schemeCode: "119598",
    fundName: "SBI Bluechip Fund - Direct Growth",
    category: "Large Cap Equity",
    vintageYears: 11,
    risk: "Above Average",
    historicalReturn3Y: 14.8,
    historicalReturn5Y: 14.1,
    currentNav: 106.06,
    expenseRatio: 0.85,
    aum: "₹42,100 Cr",
    reason: "Invests in stable market leaders. Perfect for standard risk profile seeking consistent compounding matching Nifty index growth.",
    similarFunds: ["ICICI Prudential Bluechip", "HDFC Top 100"]
  },
  {
    schemeCode: "119063",
    fundName: "HDFC Nifty 50 Index Fund - Direct Growth",
    category: "Index Fund (Equity)",
    vintageYears: 10,
    risk: "High",
    historicalReturn3Y: 15.2,
    historicalReturn5Y: 14.8,
    currentNav: 240.49,
    expenseRatio: 0.20,
    aum: "₹12,800 Cr",
    reason: "Low expense ratio, replicates Nifty 50. Excellent choice for solid low-cost long-term passive index investing.",
    similarFunds: ["UTI Nifty 50 Index", "ICICI Pru Nifty 50"]
  },
  {
    schemeCode: "120251",
    fundName: "ICICI Prudential Equity & Debt Fund - Direct Growth",
    category: "Aggressive Hybrid",
    vintageYears: 11,
    risk: "Moderate",
    historicalReturn3Y: 18.4,
    historicalReturn5Y: 16.9,
    currentNav: 459.17,
    expenseRatio: 1.1,
    aum: "₹35,600 Cr",
    reason: "Combines stability of high quality debt with high equity upside. Dynamic asset allocation limits downside risk.",
    similarFunds: ["HDFC Balanced Advantage", "SBI Equity Hybrid"]
  }
];
