export interface RegistryEntry {
  name: string;
  ticker: string;
  country: string;
  exchange: string;
  sector: string;
}

export const VERIFIED_SYMBOL_REGISTRY: RegistryEntry[] = [
  // US tech benchmarks
  { name: "Google", ticker: "GOOG", country: "United States", exchange: "NASDAQ", sector: "Technology" },
  { name: "Alphabet (Class C)", ticker: "GOOG", country: "United States", exchange: "NASDAQ", sector: "Technology" },
  { name: "Alphabet (Class A)", ticker: "GOOGL", country: "United States", exchange: "NASDAQ", sector: "Technology" },
  { name: "Apple", ticker: "AAPL", country: "United States", exchange: "NASDAQ", sector: "Technology" },
  { name: "Microsoft", ticker: "MSFT", country: "United States", exchange: "NASDAQ", sector: "Technology" },
  { name: "Tesla", ticker: "TSLA", country: "United States", exchange: "NASDAQ", sector: "Automotive" },
  { name: "Nvidia", ticker: "NVDA", country: "United States", exchange: "NASDAQ", sector: "Technology" },
  { name: "Amazon", ticker: "AMZN", country: "United States", exchange: "NASDAQ", sector: "E-Commerce" },
  { name: "Meta Platforms", ticker: "META", country: "United States", exchange: "NASDAQ", sector: "Technology" },
  { name: "Netflix", ticker: "NFLX", country: "United States", exchange: "NASDAQ", sector: "Entertainment" },
  { name: "AMD", ticker: "AMD", country: "United States", exchange: "NASDAQ", sector: "Technology" },

  // Indian equities
  { name: "Tata Consultancy Services", ticker: "TCS.NS", country: "India", exchange: "NSE", sector: "IT Services" },
  { name: "TCS", ticker: "TCS.NS", country: "India", exchange: "NSE", sector: "IT Services" },
  { name: "Reliance Industries", ticker: "RELIANCE.NS", country: "India", exchange: "NSE", sector: "Energy & Conglomerate" },
  { name: "Reliance", ticker: "RELIANCE.NS", country: "India", exchange: "NSE", sector: "Energy & Conglomerate" },
  { name: "Infosys", ticker: "INFY.NS", country: "India", exchange: "NSE", sector: "IT Services" },
  { name: "Infosys Limited", ticker: "INFY.NS", country: "India", exchange: "NSE", sector: "IT Services" },
  { name: "HDFC Bank", ticker: "HDFCBANK.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "HDFC Bank Limited", ticker: "HDFCBANK.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "State Bank of India", ticker: "SBIN.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "SBI", ticker: "SBIN.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "Suzlon Energy", ticker: "SUZLON.NS", country: "India", exchange: "NSE", sector: "Renewable Energy" },
  { name: "Suzlon", ticker: "SUZLON.NS", country: "India", exchange: "NSE", sector: "Renewable Energy" },
  { name: "Yes Bank", ticker: "YESBANK.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "HCL Technologies", ticker: "HCLTECH.NS", country: "India", exchange: "NSE", sector: "IT Services" },
  { name: "Wipro", ticker: "WIPRO.NS", country: "India", exchange: "NSE", sector: "IT Services" },
  { name: "IDFC First Bank", ticker: "IDFCFIRSTB.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "Inox Wind", ticker: "INOXWIND.NS", country: "India", exchange: "NSE", sector: "Renewable Energy" },
  { name: "Tata Power", ticker: "TATAPOWER.NS", country: "India", exchange: "NSE", sector: "Utilities" },
  { name: "Adani Enterprises", ticker: "ADANIENT.NS", country: "India", exchange: "NSE", sector: "Conglomerate" },
  { name: "Indian Oil Corporation", ticker: "IOC.NS", country: "India", exchange: "NSE", sector: "Energy" },
  { name: "Larsen & Toubro", ticker: "LT.NS", country: "India", exchange: "NSE", sector: "Construction" },
  { name: "Tata Motors", ticker: "TATAMOTORS.NS", country: "India", exchange: "NSE", sector: "Automotive" },
  { name: "Mahindra & Mahindra", ticker: "M&M.NS", country: "India", exchange: "NSE", sector: "Automotive" },
  { name: "Maruti Suzuki", ticker: "MARUTI.NS", country: "India", exchange: "NSE", sector: "Automotive" },
  { name: "Bajaj Auto", ticker: "BAJAJ-AUTO.NS", country: "India", exchange: "NSE", sector: "Automotive" },
  { name: "Sun Pharmaceutical", ticker: "SUNPHARMA.NS", country: "India", exchange: "NSE", sector: "Pharmaceuticals" },
  { name: "Dr. Reddy's Laboratories", ticker: "DRREDDY.NS", country: "India", exchange: "NSE", sector: "Pharmaceuticals" },
  { name: "Cipla", ticker: "CIPLA.NS", country: "India", exchange: "NSE", sector: "Pharmaceuticals" },
  { name: "Apollo Hospitals", ticker: "APOLLOHOSP.NS", country: "India", exchange: "NSE", sector: "Healthcare" },
  { name: "Hindustan Unilever", ticker: "HINDUNILVR.NS", country: "India", exchange: "NSE", sector: "FMCG" },
  { name: "ITC Limited", ticker: "ITC.NS", country: "India", exchange: "NSE", sector: "FMCG" },
  { name: "ITC", ticker: "ITC.NS", country: "India", exchange: "NSE", sector: "FMCG" },
  { name: "Nestle India", ticker: "NESTLEIND.NS", country: "India", exchange: "NSE", sector: "FMCG" },
  { name: "Britannia Industries", ticker: "BRITANNIA.NS", country: "India", exchange: "NSE", sector: "FMCG" },
  { name: "ICICI Bank", ticker: "ICICIBANK.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "ICICI Bank Limited", ticker: "ICICIBANK.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "Kotak Mahindra Bank", ticker: "KOTAKBANK.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "Axis Bank", ticker: "AXISBANK.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "Punjab National Bank", ticker: "PNB.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "Bank of Baroda", ticker: "BANKBARODA.NS", country: "India", exchange: "NSE", sector: "Banking" },
  { name: "Bajaj Finance", ticker: "BAJFINANCE.NS", country: "India", exchange: "NSE", sector: "Financial Services" },
  { name: "Bajaj Finserv", ticker: "BAJAJFINSV.NS", country: "India", exchange: "NSE", sector: "Financial Services" },
  { name: "Jio Financial Services", ticker: "JIOFIN.NS", country: "India", exchange: "NSE", sector: "Financial Services" },
  { name: "Bharti Airtel", ticker: "BHARTIARTL.NS", country: "India", exchange: "NSE", sector: "Telecom" },
  { name: "Airtel", ticker: "BHARTIARTL.NS", country: "India", exchange: "NSE", sector: "Telecom" },
  { name: "NTPC", ticker: "NTPC.NS", country: "India", exchange: "NSE", sector: "Utilities" },
  { name: "Power Grid Corporation", ticker: "POWERGRID.NS", country: "India", exchange: "NSE", sector: "Utilities" },
  { name: "Coal India", ticker: "COALINDIA.NS", country: "India", exchange: "NSE", sector: "Energy & Mining" },
  { name: "UltraTech Cement", ticker: "ULTRACEMCO.NS", country: "India", exchange: "NSE", sector: "Materials" },
  { name: "Titan Company", ticker: "TITAN.NS", country: "India", exchange: "NSE", sector: "Consumer Goods" },
  { name: "Titan", ticker: "TITAN.NS", country: "India", exchange: "NSE", sector: "Consumer Goods" },
  { name: "Hindustan Aeronautics", ticker: "HAL.NS", country: "India", exchange: "NSE", sector: "Defense" },
  { name: "HAL", ticker: "HAL.NS", country: "India", exchange: "NSE", sector: "Defense" },
  { name: "Bharat Electronics", ticker: "BEL.NS", country: "India", exchange: "NSE", sector: "Defense" },
  { name: "BEL", ticker: "BEL.NS", country: "India", exchange: "NSE", sector: "Defense" },
  { name: "Adani Green Energy", ticker: "ADANIGREEN.NS", country: "India", exchange: "NSE", sector: "Renewable Energy" },
  { name: "Adani Power", ticker: "ADANIPOWER.NS", country: "India", exchange: "NSE", sector: "Utilities" },
  { name: "IREDA", ticker: "IREDA.NS", country: "India", exchange: "NSE", sector: "Financial Services" },
  { name: "Tata Steel", ticker: "TATASTEEL.NS", country: "India", exchange: "NSE", sector: "Metals" },
  { name: "JSW Steel", ticker: "JSWSTEEL.NS", country: "India", exchange: "NSE", sector: "Metals" },
  { name: "Hindalco Industries", ticker: "HINDALCO.NS", country: "India", exchange: "NSE", sector: "Metals" },
  { name: "Vedanta Limited", ticker: "VEDL.NS", country: "India", exchange: "NSE", sector: "Metals" }
];
